### ISSUE TITLE
Empty List value causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-shell#120] opened 2017-04-17 19:39 UTC
When adding a Table value that consists of an empty `List<String>()`, I am encountering an `ArrayIndexOutOfBoundsException` when rendering the Table.

```java
modelBuilder.addRow().addValue("Roles").addValue(new ArrayList<String>());
...
builder.build().render(600);
```

```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.springframework.shell.table.SimpleVerticalAligner.align(SimpleVerticalAligner.java:81)
	at org.springframework.shell.table.Table.render(Table.java:136)
	at org.springframework.cloud.dataflow.shell.command.ConfigCommands.info(ConfigCommands.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
	at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
	at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
	at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
	at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ericbottard** [comment] 2017-06-28 13:46
Couldn't reproduce, seems like this has nothing to do with the empty list.
Closing for now, as I'm in the process of tidying the shell GH repo

**Closed by ericbottard** 2017-06-28 13:46 UTC
