### ISSUE TITLE
Spring command line arguments clashe with spring shell command line arguments

### ISSUE THREAD

**Issue by Kruschenstein** [spring-projects/spring-shell#963] opened 2023-12-28 13:07 UTC
I wrote a tiny command-line tool to handle some stuff in my project. This tool uses `application.yaml` to connect to database and do it's job. Because I have many environment, I decide to externalize the environment configuration in different `application.yaml`. However, if I pass the `application.yaml` file on the command line argument with `--spring.config.location=file:application.yaml`, spring framework load it nicely, but then the argument is given to spring-shell which don't recognize the pattern and crash the app.

I wrote a whole tiny project to illustrate. You can found it here : [tiny-project](https://github.com/Kruschenstein/spring-shell-command-line-arguments). All is written in the `README.md`.

I think it would be nice if the default spring framework command line arguments were ignored or were marked as handled or something else instead of crashing the whole app ^^

**Comment by jvalkeal** [comment] 2024-01-02 09:23
Duplicate of #508

**Closed by jvalkeal** 2024-01-02 09:23 UTC
Labels: status/duplicate

**Comment by mirkobeine** [comment] 2024-07-01 08:02
I was able to solve this with a workaround, specifically by configuring a custom ShellRunner that decorates the given ShellRunner-implementation and simply filtering the args passed to the run -Method of the decorated [ShellRunner-implementation](https://docs.spring.io/spring-shell/docs/3.1.4/docs/index.html#using-shell-execution-shellrunner).

However, I think it should be possible to filter args automatically by utilising the CommandCatalog, passing only those args to the shell that match a command or an option registered in the CommandCatalog.

Any thoughts on that idea by the maintainers? I could probably create a feature request and provide a PR.
