### ISSUE TITLE
Failed to convert from type [java.lang.String] to type [java.lang.Integer]

### ISSUE THREAD

**Issue by ateequrrahman97** [spring-projects/spring-shell#485] opened 2022-07-27 13:59 UTC
Hi @jvalkeal 
I hope you are doing good.

I am facing this error after moving to 2.1.0 in my project.

![Screenshot from 2022-07-27 18-56-38](https://user-images.githubusercontent.com/74288984/181265750-3c848056-164c-4710-a8d2-1251d696988b.png)

Can you please tell me the cause of this error?
In the previous version, it will work running.

**Comment by jvalkeal** [comment] 2022-07-27 14:29
You need to show how method is defined or provide a sample.

**Comment by ateequrrahman97** [comment] 2022-07-27 14:45
> You need to show how method is defined or provide a sample.

![Screenshot from 2022-07-27 19-43-51](https://user-images.githubusercontent.com/74288984/181276965-e5d9c49f-2c86-4155-bb51-b9c1d8184a76.png)

And implementation
`orderSide.toUpperCase(Locale.ROOT),`

**Comment by ateequrrahman97** [comment] 2022-07-27 15:08
@jvalkeal 
Also, it will not clean install and not run test cases.

![Screenshot from 2022-07-27 20-07-44](https://user-images.githubusercontent.com/74288984/181282603-5a1e9269-7567-45f6-8dad-390efe4d1134.png)

**Comment by jvalkeal** [comment] 2022-07-27 15:17
I quickly tried and was unable to reproduce. Can you create a simple runnable sample project where we can see this failure.

**Comment by ateequrrahman97** [comment] 2022-07-27 15:24
> I quickly tried and was unable to reproduce. Can you create a simple runnable sample project where we can see this failure.
Sure but the point is why this version is not so well with the existing code.
When I move back to the previous version code works well. mvn clean install also compiles the code smoothly.

**Comment by jvalkeal** [comment] 2022-07-27 15:34
Think I found how to get into this same error. Lemmy try to figure it out as this was probably due to gnu single parameter support like having `-a` and `-b` then in some cases those can be combined into `-ab`.

**Comment by jvalkeal** [comment] 2022-07-28 09:12
Root cause indeed is new behaviour with short options. I'm closing this in favour of #487. We'll see what comes out from that.

**Closed by jvalkeal** 2022-07-28 09:12 UTC
